name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow-dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install Dependencies
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim ~/.local/share/nvim/site/pack/vendor/start/telescope.nvim

      - name: Run Tests
        run: |
          nvim --headless -c "PlenaryBustedDirectory lua/linear-nvim/tests/ {minimal_init = 'tests/minimal_init.lua'}"
